spring:
  datasource:
    name: dev-server
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pawfectly_yours_db
    username: root
    password: root
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: "true"
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  servlet:
    context-path: /api/vet-tracker
  port: 5004
allowed:
  origin: http://localhost:5173